DiscipleTools/disciple-tools-theme

- assets/js/list-contacts.js
> Contacts List: Show name for dispatch || user || group

- assets/functions/enqueue-scripts.php
- assets/js/notifications.js
- template-notifications.php
Added javascript enqueue, new javascript functions, and page style
> Notifications page

- single-locations.php
This is a minor typo edit to the p2p call on the archive-locations.php page.
> Updated p2p mismatch

- template-settings.php
I’m pushing this commit, because it doesn’t appear this patch has been passed to master. Should correct the template-settings.php
> Settings: Patch to template-settings.php

- assets/functions/class-tgm-plugin-activation.php
Issue is referenced here
https://github.com/DiscipleTools/disciple-tools-theme/issues/57
> Patch: TGMPA plugin required a small patch for WP 4.8

- assets/js/notifications.js
- template-notifications.php
Added all and unread listings
Moved list to API query
> Final notifications

- assets/js/notifications.js
This is a minor logic addition to the handling of null query responses to the notifications list.
> Minor corrections to null queries on notifications page

- assets/js/notifications.js
- template-notifications.php
- template-settings.php
- template-workers.php
This takes the same logic as on the settings page and repeats it for the workers page.
> Added listing of workers on the workers page

- assets/functions/enqueue-scripts.php
- assets/functions/menu.php
- assets/js/metrics.js
- template-metrics.php
Remade the metrics page
Added metrics.js
Added enqueue
Put in some placeholder content so we can confirm UI/UX
> Added metrics page layout and sample scripting

- assets/functions/enqueue-scripts.php
- assets/js/metrics.js
- template-metrics.php
- template-workers.php
Development into the metrics section.
> Metrics: Basic charting draft

- LICENSE
- dependencies/lodash/LICENSE
- dependencies/typeahead/LICENSE
- style.css
Based on the Git history of this project, this project only has three authors so far:
- @ChrisChasm 
- @corsacca
- @burntsun
So it's my determination that these are the only copyright holders (ignoring the included libraries).
This should get merged in once this other pull request gets accepted and the authors agree to the relicensing: https://github.com/DiscipleTools/disciple-tools/pull/223
> Relicense to gplv2 or later

- assets/functions/enqueue-scripts.php
- assets/js/api-wrapper.js
- assets/js/contact-details.js
This fixes this issue: https://github.com/DiscipleTools/disciple-tools/issues/220
A few of the commits are there just for refactoring. You may want to view this pull request commit by commit.
>  Add "created contact" activity item in contact details

- assets/js/metrics.js
Added all but prayer, social, and web elements of the critical path.
https://github.com/DiscipleTools/disciple-tools/issues/245
> Added 2/3 critical path elements

- dt-contacts/contacts-post-type.php
- dt-contacts/contacts.php
- dt-core/logging/class-activity-api.php
- dt-core/logging/hooks/class-hook-posts.php
- dt-core/migrations/0001-add-activity-column.php
- dt-core/posts.php
- dt-groups/groups.php
- functions.php
See if this works for you. All now activity should be translated, the existing activity doesn't have some required fields.
> translate activity messages

- dt-assets/functions/enqueue-scripts.php
- dt-assets/js/contact-details.js
- dt-assets/parts/contact-details.php
- dt-contacts/contacts-post-type.php
- dt-contacts/contacts.php
- dt-core/config-p2p.php
- dt-core/posts.php
@ChrisChasm do you want to have a look at this before i merge?
> Add sub assigned field. Closes #320

- dt-assets/parts/contact-details.php
- single-contacts.php
I think it looks a little cleaner...
> Add some margin to the update needed notification

- dt-contacts/contacts.php
- dt-core/admin/config-site-defaults.php
- dt-core/admin/menu/tabs/tab-general.php
- dt-workflows/update-required.php
> Update needed Tool

- dt-groups/groups.php
- dt-notifications/hooks/class-hook-comments.php
- dt-notifications/notifications-email.php
- dt-notifications/notifications.php
This will make the emails group better in Gmail's web interface.
> Change email subject to always be "Update..."

- .gitignore
- dt-users/users.php
- template-settings.php
For the email, I did not currently add any safety measures to stop a malicious actor with temp access with the account from changing the email.
> Fix for ISSUSE #558 also did ISSUE #504

- dt-assets/parts/merge-details.php
> removing preg_grep

- dt-assets/js/comments.js
- dt-assets/parts/merge-details.php
- dt-contacts/contacts.php
- single-contacts.php
Here is the latest update to Merge Contacts tool.
> Modification to Merge Contacts tools

- dt-core/config-p2p.php
- dt-locations/locations.php
- dt-metrics/metrics-users.js
- dt-users/users-template.php
- template-settings.php
upgraded settings page to include locations from contact.
hide none working parts of user activity report.
> completed locations roll up report.

- archive-contacts.php
- dt-assets/parts/nav-offcanvas-topbar.php
Changed the mobile search icon from black to white and added the "Create New" dropdown next to notifications and settings on mobile.
> Made the mobile top bar work more correctly

- dt-contacts/contacts.php
This is in order to speed up some code outside of this plugin that used
to call `get_contact`
> Refactor code out of get_contact

- dt-assets/js/contact-details.js
- dt-assets/js/footer-scripts.js
- dt-assets/js/group-details.js
- dt-assets/js/notifications.js
- dt-assets/js/settings.js
- dt-assets/js/shared-functions.js
Mainly add a global function to make a request via jquery, `makeRequest()`, rather than calling it with the same general parameters. Refactors the `window.API` object and other places to implement this function.
> JS Cleanup

- dt-assets/js/contact-details.js
- dt-assets/js/group-details.js
- dt-assets/js/list.js
- dt-assets/parts/contact-details.php
- dt-assets/parts/group-details.php
- dt-contacts/contacts.php
- dt-core/admin/config-site-defaults.php
- dt-core/global-functions.php
- dt-core/posts.php
- dt-groups/groups.php
- dt-metrics/counter.php
- dt-metrics/metrics-prayer.js
- dt-metrics/metrics-project.php
- dt-users/users.php
- functions.php
- template-merge-details.php
Fix xxs and other security issues.
> Improve Security

- dt-assets/functions/enqueue-scripts.php
- dt-assets/parts/contact-details.php
- dt-assets/parts/contact-quick-buttons.php
- dt-assets/parts/group-details.php
- dt-assets/parts/loop-activity-comment.php
- dt-contacts/contacts-post-type.php
- dt-contacts/contacts.php
- dt-core/admin/config-site-defaults.php
- dt-groups/groups-post-type.php
- dt-groups/groups.php
- dt-notifications/notifications-email.php
- functions.php
- single-contacts.php
- single-groups.php
Caching, disabling some file including and tweaks.
> Make D.T faster

- dt-contacts/contacts-post-type.php
- dt-core/migrations/0025-post-user-meta.php
- dt-posts/dt-posts.php
- dt-posts/posts.php
- functions.php
- tests/after-unit-tests.php
- tests/unit-test-contacts-groups.php
Ability to store personal information related to a record.
> User post meta

- dt-mapping/mapping-module-config.php
- dt-mapping/mapping.php
Changed the capability from 'read_location' to 'view_mapping……'. Also, added a permission check that will be present even if loaded via REST.
> Mapping: Mapping permission fix

- dt-assets/parts/modals/modal-help.php
> Groups: update help modal

- dt-assets/functions/enqueue-scripts.php
- dt-mapping/columns/add-churches-column.php
- dt-mapping/columns/add-contacts-column.php
- dt-mapping/columns/add-groups-column.php
- dt-mapping/columns/add-users-column.php
- dt-mapping/drill-down.js
- dt-mapping/globals.php
- dt-mapping/loader.php
- dt-mapping/mapping-admin.php
- dt-mapping/mapping-metrics.js
- dt-mapping/mapping-metrics.php
- dt-mapping/mapping-queries.php
- dt-mapping/mapping.css
- dt-mapping/mapping.js
- dt-mapping/mapping.php
- dt-metrics/contacts/milestones-map.php
- dt-metrics/contacts/milestones_map.js
- dt-metrics/metrics.php
Update drilldown to give access to world when a focus is set.
Add milestones map to view milestone breakout by location.
> Mapping: modularize metrics map.

- dt-assets/parts/contact-details.php
changed from esc_html to esc_html_e for the Email and Phone label
> changed the Phone and Email Labels for internationalization

- dt-core/migrations/0029-activity-log-index.php
- dt-mapping/class-migration-engine.php
- dt-mapping/globals.php
- functions.php
Run theme migrations and then the mapping migrations.
> Fix migration order.

- dt-contacts/contacts-post-type.php
- dt-groups/groups-post-type.php
Added contact type field for expansion of the location_grid data collected with the Map Box extension.
> Mapping: Added supporting field type for Location Grid Mapbox upgrade.

- dt-notifications/notifications.php
- dt-people-groups/people-groups.php
- dt-posts/posts.php
- dt-users/users-endpoints.php
- dt-users/users.php
- template-settings.php
I think I have found all the instances of get_user_locale that needed to be changed.
> Get user locale

- template-contacts-new.php
- template-groups-new.php
> Add focus on first modal input

- dt-contacts/contacts-transfer.php
- dt-core/admin/site-link-post-type.php
Removed the word transfer from the URL.
Added a link to the developer wiki.
> closes #917 Site link documentation

- dt-assets/functions/menu.php
- dt-assets/parts/nav-offcanvas-topbar.php
- dt-users/template-user-management.php
- dt-users/user-management.js
- dt-users/user-management.php
> Mapbox integration

- dt-assets/functions/enqueue-scripts.php
> changed string from "created record at" to "created record on"

- dt-assets/js/comments.js
- dt-assets/js/contact-details.js
- dt-assets/js/details.js
- dt-assets/js/group-details.js
- dt-assets/js/shared-functions.js
- dt-assets/parts/group-details.php
- dt-contacts/contacts-template.php
- dt-posts/posts.php
- single-contacts.php
- single-groups.php
> Group date formatting

- dt-contacts/contacts-template.php
- single-groups.php
they now use the new formatting with the button to clear the input, based on @blachawk earlier changes
> updated the custom field data pickers 

- dt-core/admin/class-roles.php
The dispatcher should not have the permission to activate/disactivate plugins and manage other D.T settings
> Distpatcher manage_dt permissions. 

- dt-assets/js/contact-details.js
- dt-assets/js/details.js
- dt-assets/js/list.js
- dt-assets/js/modular-list.js
- dt-assets/js/shared-functions.js
This is done by converting them to latin digits before we process them.
> Allow typing Arabic or Persian numbers and dates into Date fields

- dt-core/admin/site-link-post-type.php
This will more closely simulate how contact transfer works so that those using IP whitelist can get properly setup
> Perform site link check from backend

- dt-users/users.php
Allows the insertion of custom tagging options in comments by plugins
> Add filter for assignable users

- dt-core/admin/site-link-post-type.php
**Use case:**
Our hosting implements IP whitelisting at the firewall to prevent unwanted traffic. In order to authorize site link traffic via the API, we need to know the server IP address that requests will be coming from. This adds a button to make a request to ifconfig.co/ip to get the server's IP address since it cannot be consistently retrieved from PHP server variables because of varying hosting methods (i.e. Apache vs. nginx, basic single hosted site vs. load balancing, etc.)
> Add button to fetch server IP address while creating/editing site link

- archive-contacts.php
- dt-assets/js/list.js
- dt-network/network.php
Added action to contacts-archive page
Added a window store for list js
> List exports expansion

- dt-core/admin/site-link-post-type.php
> Site Links - Site URL incorrect for subdirectory multi-sites

- dt-assets/functions/cleanup.php
Fixed styling for commented functions
> Contact types

- archive-template.php
- dt-assets/functions/enqueue-scripts.php
- dt-assets/js/modular-list.js
Fixed Bulk edit for location fields.
Also fixes a couple of bugs in other Bulk Edit features.
Closes #1090
> Bulk edit location

- single-template.php
reported by @mikeallbutt in Slack
https://disciple-tools.slack.com/archives/CDXNVC892/p1610835360010300
> fixes spacing issue with typeaheads in mobile

- dt-assets/js/details.js
This largely applies to the name field.
> fixes the html encoding of '&' on the input and output 

- README.md
Fixed Online Guidebook URL typo
https://disciple.tools/user-doccs -> https://disciple.tools/user-docs
> Fixed URL typo

- dt-assets/js/details.js
changes ', ' to ' / ' for multiple locations in details.
> partial fix for #1136

- template-settings.php
Fixes #1180 
Also Biography/Description label on the edit modal so it matches the main screen.
> fixes #1180

- dt-assets/functions/details-bar.php
> change the icon based on gender.

- dt-core/admin/js/dt-options.js
- dt-core/admin/menu/tabs/tab-custom-tiles.php
should resolve https://github.com/DiscipleTools/disciple-tools-theme/issues/1179, conflicts with https://github.com/DiscipleTools/disciple-tools-theme/pull/1182
> Changed `save-drag-changes` from an id to a class

- dt-assets/js/modular-list.js
> Makes links in a list CMD clickable.

- dt-core/configuration/class-migration-engine.php
- dt-core/global-functions.php
- dt-core/migrations/0040-update-reports-value-column.php
In the effort to stay DRY, I have written a version of this function into at least 6 plugins. I believe it deserves a place on the "holy" global functions page.
It creates a random has which will be used in applications that use the magic link strategy or other things that need a unique public key. SHA256.
> Key generator to global functions

- dt-assets/js/details.js
- dt-assets/js/shared-functions.js
- dt-people-groups/people-groups-post-type.php
- dt-posts/dt-posts.php
- dt-posts/posts.php
don't include links for peoplegroups typeaheads. fixes #1157
> People Group Typeahead fix

- dt-assets/js/details.js
- dt-contacts/base-setup.php
Addresses issue: https://github.com/DiscipleTools/disciple-tools-theme/issues/1209
> Record Details: Clickable social links

- dt-contacts/contacts-transfer.php
addresses #1070 by making the timeout longer.
> Contact Transfer Timeout

- dt-posts/dt-posts.php
- dt-posts/posts.php
I think this will finally put #1176 to bed.
> Fixes HTML entities in typeaheads. Fixes #1176

- dt-assets/js/details.js
This addresses the first point in #1234
> addes slashes instead of commas between people group names

- dt-assets/js/modular-list.js
> clear mobile and desktop search input when filter changes

- dt-assets/js/new-record.js
- template-new-post.php
resolves https://github.com/DiscipleTools/disciple-tools-theme/issues/1135
> add button to hide hidden fields when adding a new record

- dt-contacts/user-module.php
- dt-users/users-endpoints.php
- dt-users/users.php
You can now choose a username and role.
> Issue #1059

- dt-assets/js/details.js
- dt-assets/js/modular-list.js
- dt-assets/js/new-record.js
- dt-contacts/duplicates-merging.php
- dt-core/admin/menu/tabs/tab-custom-fields.php
- dt-core/admin/menu/tabs/tab-fields.php
- dt-core/global-functions.php
- dt-posts/posts.php
implemented the JS and PHP to create the input and save the text.
This addresses #1049.
> implemented a textarea 

- dt-assets/js/details.js
- dt-contacts/base-setup.php
- dt-groups/base-setup.php
> 1145 apply tag directly from suggest list

- dt-assets/functions/details-bar.php
- dt-contacts/base-setup.php
- dt-groups/base-setup.php
> adds the group icon to groups header bar.

- dt-mapping/mapping-queries.php
This will show the locations from as city > state > country instead of the other way around.
> switch the location order from specific to less specific

- dt-core/admin/menu/tabs/tab-custom-lists.php
> Quick Actions

- template-settings.php
> fix: centralise add unavailable dates button with inputs

- 403.php
- dt-assets/functions/enqueue-scripts.php
- dt-assets/js/request-record-access.js
- dt-assets/js/shared-functions.js
- dt-posts/dt-posts-endpoints.php
- dt-posts/dt-posts.php
On encountering a 403 permission denied page, following an attempt to try and access either an un-shared contact or group; the following flow is adopted:
- User is presented with a `Request Record Access Permission` button.
- Once clicked, a model window is shown, requesting further confirmation of request.
- Once confirmed, a comment is placed onto record's activity stream; prompting record owner to share access accordingly.
- A notification of request is also sent to initial requesting user.
> 477 - Request Record Access 403 Page Button & Flow

- dt-contacts/contacts-transfer.php
- dt-contacts/contacts.js
- dt-notifications/notifications.php
- @mention the assigned user
- Fix spinner in share modal
- make sure the transfer token is saved (to detect duplicates).
> Transfer contact fixes

- dt-core/admin/menu/tabs/tab-error-logs.php
- New user column added to Utilities (DT) Error Log table.
- User's display name is shown if a valid user id is detected.
- Empty/Blanked string for all other states.
> 1295 - Error Log Table New User Column

- dt-mapping/drill-down.js
- dt-mapping/mapping-admin.php
GUI gets updated upon editing a Geo
> Map module bug

- dt-assets/parts/nav-offcanvas.php
> Adds Help menu item to mobile menu

- header.php
> Title Tags

- dt-core/admin/menu/tabs/tab-custom-fields.php
> fixes private option saving on tag field creation

- dt-assets/js/modular-list.js
- dt-assets/js/settings.js
- dt-contacts/contacts_dmm.js
> 1312 change and fix list filters date options

- dt-assets/js/modular-list.js
> fix: get correct sort label when doing a reverse sort #1349

- dt-assets/functions/enqueue-scripts.php
- dt-contacts/contacts.js
- dt-contacts/duplicates-merging.php
> feat: add the reason closed to possible duplicates modal #698

- dt-posts/posts.php
> add private post meta to the sorting lists.

- dt-core/configuration/restrict-rest-api.php
- dt-reports/magic-url-base.php
- dt-reports/magic-url-class.php
These edits to the magic link change the strategy of the allowed_js and allowed_css lists to a filter strategy, so that plugin developers can increase or decrease default pack of scripts depending on application.
> Magic l ink modifications

- dt-core/admin/config-dashboard.php
Checks to see if WordPress Address URL is HTTPS.
> Added HTTPS check

- dt-assets/js/comments.js
- dt-posts/dt-posts.php
- dt-posts/posts.php
Makes connections to other records clickable from the activity:
Instead of being plain text, activity messages would be in this format:
Text `[title](link)`
> Links in activity

- dt-core/admin/config-dashboard.php
- dt-core/admin/menu/tabs/tab-featured-extensions.php
Update details:
- Items are dismissible 
- Setup Wizard box is now collapsable
- Collapsable box shows description
- Collapsable box shows an 'un-dismiss' button if the item has been dismissed
- Completed and/or dismissed items get a green checkbox
- Completed and/or dismissed items get sent to the bottom of the list
Corresponds to some elements in https://github.com/DiscipleTools/disciple-tools-theme/issues/1382
> Setup Wizard Updates

- dt-assets/js/comments.js
- dt-core/configuration/config-site-defaults.php
Updated emojis according to https://github.com/DiscipleTools/disciple-tools-theme/issues/1324
> Updated emojis

- dt-contacts/base-setup.php
- dt-groups/base-setup.php
- dt-notifications/notifications-email.php
- dt-notifications/notifications.php
- dt-posts/dt-posts.php
- dt-posts/posts.php
> 1386 fix emails sent in correct locale

- dt-notifications/notifications.php
- dt-users/users-endpoints.php
- dt-users/users.php
resolves #1413 
resolves #1427 
resolves #1428
> feat: add filter to translate add user email #1413

- archive-template.php
- dt-assets/functions/enqueue-scripts.php
- dt-assets/js/modular-list.js
- dt-posts/posts.php
> feat: add without e.g. 'baptized by' option to connection filters #695

- dt-core/admin/menu/tabs/tab-featured-extensions.php
Revamped DT Extensions page. New UI reflects that of the "add new plugin" admin page.
- Tested installs
- Tested activations
- Tested deactivations
PHPCS throws false positives.
> Plugin gallery UI

- dt-assets/js/new-record.js
> feat: finish autofocus forms issue #897

- dt-contacts/user-module.php
- dt-core/admin/menu/tabs/tab-general.php
- dt-users/template-new-user.php
- dt-users/user-management.js
- dt-users/user-management.php
- dt-users/users-endpoints.php
- dt-users/users.php
- single-template.php
- template-settings.php
> feat: strategy for letting multipliers make multipliers

- dt-core/admin/js/dt-utilities-scripts.js
- dt-core/admin/menu/tabs/tab-custom-fields.php
- dt-core/admin/menu/tabs/tab-custom-lists.php
- dt-core/admin/menu/tabs/tab-scripts.php
> #1508 & #1509 - Support Field Icon Uploads

- dt-assets/js/notifications.js
- dt-assets/parts/nav-topbar.php
- dt-notifications/notifications-endpoints.php
- dt-notifications/notifications.php
- template-notifications.php
> #1514 - Filter Notifications By @Mentions

- header.php
Added fix for mobile zooming on focus.
> Add more definition to mobile view to prohibit browser zoom.

- dt-users/template-user-management.php
- dt-users/user-management.js
> #1537 - Updated User Management Table

- dt-core/admin/menu/tabs/tab-general.php
- dt-core/configuration/config-site-defaults.php
- dt-notifications/notifications-email.php
> #1551 - Ability To Specify Alternative From Email Addresses

- composer.json
- dt-core/admin/site-link-post-type.php
- dt-core/global-functions.php
- dt-posts/dt-posts.php
- tests/dt-posts/dt-posts/unit-test-post-comments.php
> #1561 - API Comments Date Format Validation

- dt-core/admin/js/dt-utilities-scripts.js
- dt-core/admin/menu/tabs/tab-custom-fields.php
- dt-core/admin/menu/tabs/tab-scripts.php
> #1571 - Color Picker To Change Key Select Option Colors

- dt-core/admin/menu/tabs/tab-custom-fields.php
- dt-core/admin/menu/tabs/tab-general.php
- dt-core/configuration/config-site-defaults.php
> #1044 - Custom Seeker Path Option Triggers Support

- dt-assets/js/advanced-search.js
- dt-assets/parts/modals/modal-advanced-search.php
> #1589 - Advanced Search Upgrades

- dt-assets/functions/details-bar.php
- dt-assets/js/details.js
- dt-assets/parts/loop-activity-comment.php
- dt-contacts/access-module.php
- dt-core/global-functions.php
This currently doesn't work if someone is sub assigned to a contact.
> disable inputs if user can view a post but not update it.

- dt-reports/magic-url-endpoints.php
- dt-reports/magic-url-setup.php
> #1629 - Magic Links > Apps Tile > Send Email with Link

- dt-assets/parts/nav-topbar.php
- dt-core/admin/menu/tabs/tab-general.php
Add a custom logo to your DT instance
Corresponds to https://github.com/DiscipleTools/disciple-tools-theme/issues/1588
**Configurable from the Admin DT Settings page**
<br>
**Example Screeshot**
> Custom logo

- dt-assets/js/modular-list.js
> #1604 - Lists: Closing A Text Search

- dt-groups/groups.js
Responds to: #1398 
**Current behavior:**
- Black Footstep icon removed for leaders
- Leader toggle footstep icon is now black if member is leader
> Cleaned up leader footstep ui in 'Member List' tile

- archive-template.php
- dt-assets/js/modular-list.js
- dt-contacts/base-setup.php
- dt-groups/base-setup.php
> feat: add a toggle into the list page #1578

- dt-core/admin/menu/tabs/tab-fields.php
> #1619 - Remember Post Type WPAdmin Selection

- dt-assets/js/details.js
- dt-assets/js/modular-list.js
- dt-assets/js/shared-functions.js
> feat: list page filter from url query params

- dt-core/admin/menu/tabs/tab-custom-fields.php
> #1638 - Enabled Icon Uploads For Custom Fields

- dt-assets/js/modular-list.js
> feat: collapse filter tile on mobile view

- dt-assets/js/comments.js
- dt-assets/parts/loop-activity-comment.php
> fix: always show the comments and activity checkbox filters

- dt-core/admin/menu/tabs/tab-custom-tiles.php
- dt-core/admin/menu/tabs/tab-general.php
- dt-groups/base-setup.php
- dt-posts/dt-posts.php
- single-template.php
> feat: hide tiles set by group tile preferences

- dt-core/admin/menu/tabs/tab-fields.php
> feat: field explorer upgrades

- dt-core/admin/js/dt-options.js
- dt-core/admin/menu/tabs/tab-custom-fields.php
- dt-core/global-functions.php
> #1650 - Support Draggable Field Options

- dt-assets/js/modular-list.js
put top level blocks of code into self describing functions
also move all on page load functionality into one function
> refactor: modular-list.js

- dt-assets/js/shared-functions.js
- dt-assets/parts/modals/modal-help.php
- dt-reports/magic-url-setup.php
> feat: add tooltips to magic link buttons in app links tile

- dt-assets/js/modular-list.js
changes to proper functions so they get hoisted and can be accessed fixing a bug on all modular lists except contacts
> Modular List Bug Fix

- dt-core/admin/admin-enqueue-scripts.php
- dt-core/admin/js/dt-options.js
- dt-core/admin/menu/tabs/tab-custom-fields.php
- dt-core/admin/menu/tabs/tab-custom-lists.php
- dt-core/admin/menu/tabs/tab-custom-tiles.php
> #1651 - Support Admin Custom Translation Modal Views

- dt-core/global-functions.php
> #1661 - Support Language Flags

- dt-mapping/geocode-api/ipstack-api.php
Found a bug in the get_location_grid_meta_from_current_visitor() function where it was collecting the ip address from the server and not the user.
> Ipstack api fix

- dt-core/admin/menu/tabs/tab-custom-fields.php
@corsacca This was something I missed when I was doing the number field
resolves #1686
> docs: add number field to list of available fields in admin area

- .husky/pre-commit
- .travis.yml
- package-lock.json
- package.json
- phpcbf.sh
> chore: add husky and lint-staged to lint staged php files

- dt-users/template-new-user.php
- dt-users/user-management.php
> #1691 - Adding User 404 Exception Multisite Support

- dt-posts/dt-posts.php
- dt-posts/posts.php
> #1647 - Support Address Geocoding On API Entry

- dt-assets/js/details.js
- dt-posts/posts.php
@corsacca this should fix the number comparison issue
> fix: change min max comparisons to parse to int

- dt-posts/posts.php
- tests/dt-posts/dt-posts/unit-test-list-posts.php
> #1728 - Fix List Number Query

- dt-workflows/workflows-execution-handler.php
- dt-workflows/workflows-triggers.php
> #1743 - Workflow Actioned Following Conditional Field Trigger

- dt-posts/dt-posts.php
- dt-workflows/workflows-execution-handler.php
- dt-workflows/workflows-triggers.php
> #1741 - Use Workflow Name As Activity Author

- dt-contacts/duplicates-merging.php
> #1749 - Duplicate Merging - Ignored Fields

- dt-users/user-metrics.php
> #1676 - Only Show Published Post Related Activities

- dt-assets/js/merge-post-details.js
> #1756 & #1760 - Fixed Merge Selection & Duplicate Bugs

- dt-users/users.php
> #1783 - Share Sub-Assigned Contacts When Contact Upgraded To User

- dt-contacts/base-setup.php
- dt-posts/posts.php
- dt-workflows/workflows-defaults.php
> #373 - Default Workflow To Auto Select In Church/Group Following Group Addition

- dt-posts/dt-posts.php
> #1826 - Updating Comment With No Change Throws Error

- dt-assets/parts/nav-offcanvas.php
- dt-assets/parts/nav-topbar.php
> #1832 - Fix Disappearing More Menu & Items - People Groups

- dt-core/admin/menu/tabs/tab-metrics-edit.php
> #1838 - Delete Report Button Issue Fix

- dt-core/admin/menu/tabs/tab-custom-fields.php
Corresponds to issue: https://github.com/DiscipleTools/disciple-tools-theme/issues/1853
> Fixed the if statement

- dt-core/admin/js/dt-utilities-workflows.js
- dt-core/admin/menu/tabs/tab-workflows.php
- dt-workflows/workflows-execution-handler.php
> #1836 & #1816 - Workflow Updates

- dt-core/admin/admin-enqueue-scripts.php
> #1817 - Error When Loading Icon Selector

- single-template.php
> #1844 - Unable To Create Connection With Typeahead In Details Tile 

- dt-users/user-hooks-and-config.php
Small condition I found throwing an error where the response is WP_Error.
> Fix: Added filter for a WP_Error response.

- dt-users/users.php
Bug was revealed working on remote user creation for Zume. Bools can be passed to these functions and throw critical errors while using the /my user endpoint
> User Map: Bool protection if an array not passed.

- dt-core/admin/js/dt-options.js
- dt-core/admin/menu/tabs/dialog-icon-selector.php
- fixes: #1871 
> Unable to re-create floating micro-break warning?
> #1871 - Icon Selector Typeahead & Overflow

- dt-assets/js/comments.js
> #1882 - Robot Icon Used For System Activity Stream Entries

- dt-core/admin/js/dt-utilities-workflows.js
- dt-core/admin/menu/tabs/tab-workflows.php
> #1890 - Ability To Delete A Workflow

- dt-metrics/combined/mapbox-maps.php
- dt-metrics/common/maps_library.js
- dt-metrics/contacts/mapbox-maps.php
- dt-metrics/groups/mapbox-maps.php
- dt-metrics/personal/mapbox-contacts-maps.php
- dt-metrics/personal/mapbox-groups-maps.php
- dt-users/mapbox-coverage-map.php
> #1872 - To View Map Metrics, Install Mapbox Key

- dt-mapping/mapping-admin.php
> #1927 - Change Mapping Tab Migration Lock To Transient

- dt-assets/js/modular-list.js
See: https://github.com/DiscipleTools/disciple-tools-survey-collection/issues/23#issuecomment-1403585611
> Load Location Typeahead No Element Fix

- dt-posts/dt-posts.php
- dt-posts/posts.php
- tests/dt-posts/dt-posts/unit-test-list-posts.php
> #1807 - Search On Complete Name Matching

- dt-groups/groups.js
> #1934 - Group Member List Ordering

- archive-template.php
- dt-posts/dt-posts.php
- single-template.php
Changes the current label to the default_label, if the user changes the custom label it will use that custom label and its translations
> Allows custom labels for the Status and Details tile.

- dt-posts/dt-posts.php
- tests/dt-posts/dt-posts/unit-test-global-search.php
> #1941 - Global Search Unit Tests

- dt-core/admin/menu/tabs/tab-general.php
- dt-users/user-initial-setup.php
- dt-users/user-management.js
- dt-users/user-management.php
- dt-users/users.php
- functions.php
- template-settings.php
- fixes: #1933 
- fixes: #1877 
- fixes: #1875 
- Please note; following release update, all users will be initially prompted to confirm their default language setting and are required to confirm; to avoid any further user setup prompts.
- Following on from this, only new users will be prompted.
> #1933 - Links To Help Translate + Other User Language Issues

- dt-core/logging/hooks/class-hook-posts.php
> #1950 - Capture Link Field Types Within Activity Record

- dt-core/admin/js/dt-extensions.js
- dt-core/admin/menu/tabs/tab-featured-extensions.php
- dt-core/core-endpoints.php
Added search feature to extensions page and improved UX/UI.
https://user-images.githubusercontent.com/36511666/222523883-f383a9a5-3750-457e-9a0e-ee6b29965258.mov
> Extensions search

- dt-core/global-functions.php
easily leave host in the path when using this function
@corsacca let me know what you think
I'm happy to copy and paste a version of this into PG in necessary
> feat: add param to dt_get_url_path to include host

- dt-posts/dt-posts.php
- tests/dt-posts/dt-posts/unit-test-create-post.php
- tests/dt-posts/dt-posts/unit-test-update-post.php
> #1969 - Support Deleting Of Number Fields With Min/Max Constraints

- dt-login/login-user-manager.php
it was creating a new user_meta on every login 🤦🏻‍♂️
> fix: multiple meta values being created for firebase_identities and uid

- dt-reports/magic-url-class.php
- dt-reports/magic-url-landing-page.php
> #1980 - Custom Invalid Link Landing Page

- dt-core/dt-route.php
ref https://disciple-tools.slack.com/archives/CQL9SK2TH/p1679321055021099?thread_ts=1678810957.863089&cid=CQL9SK2TH
> feat: add options array to adjust permission_callback etc.

- dt-core/dependencies/magic-link/magic-link-utilities.js
> #1997 - Explored PHP Echoed JS Code Alternatives

- dt-assets/js/record-history.js
- dt-posts/dt-posts.php
- fixes: #1984 
- fixes: #1990
> #1984 & #1990 - Revert Bot Updates

- dt-assets/js/details.js
> #1955 - Enabled Clickable Typeahead Multi Select Filter Queries

- dt-posts/dt-posts.php
> #2005 - Ensure Revert Activity History Dates Back To Record Start

- dt-core/admin/js/dt-settings.js
Fixed the autonavigation feature that takes you to the element from a help menu.
https://user-images.githubusercontent.com/36511666/234296576-e3fd2f10-d94f-451d-a83e-4dd7ba255768.mov
> Fixed the autonavigation feature

- archive-template.php
- dt-assets/js/modular-list.js
- dt-assets/js/shared-functions.js
- dt-posts/dt-posts-endpoints.php
- dt-posts/dt-posts.php
> #2030 - Add Split By For Current Filter

- dt-core/admin/js/dt-options.js
- dt-core/admin/menu/tabs/admin-endpoints.php
- dt-core/admin/menu/tabs/tab-custom-fields.php
- dt-core/admin/menu/tabs/tab-custom-lists.php
- dt-core/admin/menu/tabs/tab-custom-tiles.php
> #1958 - Fixed Issue Custom Field Option Translations Not Being Saved

- dt-core/admin/js/dt-settings.js
- dt-core/admin/menu/tabs/tab-customizations.php
**Misc bug fixes:**
- Tile previews normally now
- Added tile preview for textarea fields
- You can't create a tile with an empty name
- You can't edit a tile with an empty name
- You can't create a field with an empty name
- You can't edit a field with an empty name
- You can't create a field option with an empty name
- You can't edit a field option with an empty name
- Removed edit feature from the 'default blank' element in field options
> New settings misc bug fixes

- dt-users/template-user-management.php
- dt-users/user-management.js
- dt-users/user-management.php
> #1936 - Admin Link To Send User Password Reset Email

- dt-assets/js/modular-list.js
> #1814 - Show Task Notes Within List Page

- dt-metrics/combined/generation-tree.js
- dt-metrics/combined/generation-tree.php
- dt-metrics/counter.php
- dt-metrics/metrics.php
> #1798 - Dynamic Tree Generation Metrics For Connection Field Types

- dt-metrics/metrics.php
- dt-metrics/records/date-range-activity.js
- dt-metrics/records/date-range-activity.php
- dt-metrics/records/generation-tree.js
- dt-metrics/records/generation-tree.php
- dt-metrics/records/time-charts.js
- dt-metrics/records/time-charts.php
> #2128 - Added New Record Type Metrics Category

- dt-core/admin/css/disciple-tools-admin-styles.css
- dt-core/admin/css/dt-settings.css
- dt-core/admin/js/dt-settings.js
> use tags to display field details.

- dt-login/login-email.php
- dt-login/login-fields.php
- dt-login/login-user-manager.php
fixes an issue where
* SSO users didn't get a role when registering
* sso-login options now allow the admin to choose which role to give newly registering users
* on multisite the given role would get clobbered with 'subscriber' role
> Fix/dt login/add roles correctly to registering users

- dt-login/login-shortcodes.php
adds the ability to pass a language code to the dt_firebase_login_ui shortcode
> feat: add locale support to sso-login by using firebase web ui translations

- template-merge-post-details.php
> #2176 - Ensure Oldest Of The Two Records Defaults To Primary Role

- dt-core/configuration/class-migration-engine.php
- dt-core/migrations/0053-update-old-activity-log-connection-formats.php
- dt-metrics/counters/counter-post-stats.php
- dt-metrics/records/time-charts.php
> #2091 - Migrate Old Connection Activity To New Format

- dt-metrics/records/date-range-activity.php
> #2196 - Dynamic Metrics Field Activity Creation Date Not Responding

- dt-assets/parts/modals/modal-template-metrics.php
- dt-metrics/records/generation-tree.js
- dt-metrics/records/generation-tree.php
> #2185 - Generation Tree Child Addition & Node focus Support

- dt-assets/js/modular-list.js
> #2198 - Record Lists To Remember Local Storage Settings

- dt-metrics/counters/counter-post-stats.php
- dt-metrics/records/records-endpoints.php
- dt-metrics/records/time-charts.js
- dt-metrics/records/time-charts.php
> #2203 - Fields Charts - Records Change Graph

- dt-workflows/activity-log-delete-old-email-logs.php
- dt-workflows/workflows.php
- fixes: #2219 
- Delete old email sent activity logs
> #2219 - Activity Log Table Maintenance - Delete Old Email Logs

- dt-workflows/activity-log-delete-old-viewed-actions.php
- dt-workflows/workflows.php
- fixes: #2219 
- Delete old activity logs viewed actions
> #2219 - Activity Log Table Maintenance - Delete Viewed Actions

- dt-core/admin/menu/tabs/tab-utilities-overview.php
> #2227 - Utilities - Add Background Jobs Queue Counts

- dt-core/configuration/class-migration-engine.php
- dt-core/logging/class-activity-api.php
- dt-core/migrations/0054-delete-stale-array-field-type-activity-logs.php
- dt-core/migrations/0055-delete-stale-comment-activity-logs.php
- fixes: #2219 
- Migration Removal Of Comment Activity Logs
> #2219 - Activity Log Table Maintenance - Migration Removal Of Comment Activity Logs

- dt-core/admin/js/dt-settings.js
> #2242 - Customization Adding Field Translation Results In White Page

- dt-metrics/records/date-range-activity.php
> #2230 - Activity Field Day Report Zero Response

- dt-core/admin/js/dt-settings.js
- dt-posts/posts.php
> #2249 - Support Creation Of User Select Field Types

- dt-core/admin/js/dt-settings.js
> #2240 - Customizations: Disable Click Outside Of Modal To Close Modal

- dt-login/login-functions.php
> fix(login-functions): replaced spread operator ... in assosciative array

- dt-assets/js/shared-functions.js
- dt-users/users-endpoints.php
- dt-users/users.php
> #2255 - User Select List Only Users That Have Access

- dt-users/user-hooks-and-config.php
> #1973 - When Deleting A User Reassign All Their Contacts To The Base User

- dt-metrics/records/genmap.js
- dt-metrics/records/genmap.php
- fixes: #2235 
- Identifies infinite loops.
- Provides record links for identified loop elements.
> #2235 - Genmap: Infinite Loop Notice

- dt-metrics/records/genmap.js
> #2262 - Genmap Hide Tree

- dt-core/admin/admin-settings-endpoints.php
- dt-core/admin/js/dt-settings.js
- dt-core/admin/menu/tabs/tab-customizations.php
> #2260 - DT Custom Link Field Categories

- dt-core/admin/admin-settings-endpoints.php
- dt-core/admin/js/dt-settings.js
> #2266 - Limit Custom Post Type Key Characters

- dt-posts/posts.php
> #2270 - Link Field Warnings On Default Option Deletion

- dt-posts/posts.php
> #2232 - Capture Deleted Records Activity Logs

- dt-assets/js/details.js
> #2269 - Link Field Extra Line Creation

- dt-core/admin/admin-settings-endpoints.php
- dt-core/admin/js/dt-settings.js
> #2231 - List Ability To Set Default Displayed Fields [ Simplified ]

- dt-core/configuration/restrict-site-access.php
- dt-login/login-email.php
> #2281 - Standardized Reset Password Login Message

- dt-login/login-functions.php
- dt-login/login-page.php
The goal is to only load SSO settings when needed.
> Custom login rest

- dt-assets/functions/menu.php
- dt-assets/parts/nav-offcanvas.php
> Add a link to the D.T forum

- dt-assets/js/modular-list.js
- dt-posts/posts.php
> #2296 - Lists Sort By Decimal Number Not Working

- dt-users/table/users-table.js
> #2310 - User List On Mobile

- dt-notifications/email-template.html
- dt-notifications/notifications-email.php
- dt-reports/magic-url-endpoints.php
> #750 - Create An Email Template

- dt-assets/js/record-history.js
- dt-assets/parts/modals/modal-record-history.php
> #2321 - Revert Record History Progress Spinner

- dt-core/admin/admin-settings-endpoints.php
- dt-core/admin/js/dt-settings.js
> #2327 - New Custom Boolean Field Checked-By-Default Option

- dt-contacts/access-module.php
> #2328 - Keep Status Archived When Reassigning Archived Contacts

- dt-core/admin/menu/tabs/tab-general.php
- dt-workflows/update-required.php
> #2195 - Ability To Set Update Needed Triggers In Any Languages

- dt-assets/js/modular-list.js
- dt-contacts/access-module.php
- dt-contacts/base-setup.php
- dt-contacts/dmm-module.php
- dt-core/admin/menu/tabs/tab-general.php
- dt-groups/base-setup.php
> Performance mode

- dt-assets/js/modular-list.js
- dt-assets/js/shared-functions.js
> #2337 - Support Escaped HTML Characters

- dt-posts/posts.php
> #2339 - Delete Location Meta When Deleting A Record

- tests/unit-test-search-viewable-post.php
> #2349 - PHP Unit Tests

- dt-metrics/charts-base.php
- dt-metrics/records/genmap.js
> #2358 - Addressed Dynamic Metrics Gen-Map Bugs

- dt-users/template-new-user.php
- dt-users/user-management.js
> #2366 - Disabled Autocomplete

- dt-assets/js/modular-list.js
> Multiple Filtering Issue

- dt-core/global-functions.php
- dt-notifications/notifications-email.php
> #2376 - Email Template Wrapper Function

- archive-template.php
- dt-assets/functions/enqueue-scripts.php
- dt-assets/js/modular-list.js
- dt-core/admin/menu/tabs/tab-general.php
- dt-core/global-functions.php
- dt-posts/dt-posts-endpoints.php
- dt-posts/dt-posts.php
> #2342 - Bulk Send Message Core Integration

- archive-template.php
> #2402 - Enable Bulk Send Message On Any Post Type With Email

- archive-template.php
- dt-assets/js/modular-list.js
- dt-posts/dt-posts-endpoints.php
- dt-posts/dt-posts.php
> Support reply to email field

- dt-core/admin/js/dt-utilities-scripts.js
- dt-core/admin/menu/tabs/tab-imports.php
> #2408 - Admin Import - Select All Tiles & Fields

- dt-assets/functions/enqueue-scripts.php
- dt-assets/js/modular-list.js
> #2401 - Persist Zoomed Map Query Settings

- dt-core/admin/menu/tabs/tab-security.php
> Added descriptive text

- dt-metrics/records/dynamic-records-map.js
> #2435 - Dynamic Metrics - Map - Creating Layer Upgrades

- dt-reports/magic-url-setup.php
> #2460 - Upgrade Magic Link Send Email Modal

- dt-assets/js/modular-list.js
> #2463 - Lists - BCC Emails

- dt-assets/functions/details-bar.php
- dt-assets/functions/enqueue-scripts.php
- dt-assets/js/dt-storage.js
- dt-posts/dt-posts-endpoints.php
> #2462 - Added Ability To Delete Stored Images

- dt-core/admin/js/dt-settings.js
> #2409 - Only Support Creation Of Custom Location Fields

- dt-contacts/base-setup.php
- dt-groups/base-setup.php
- dt-people-groups/people-groups-base.php
- dt-posts/custom-post-type.php
> #2491 - Default Location Grid Fields

- dt-mapping/mapping-queries.php
- dt-users/users.php
> #2490 - Mapping Locations

- dt-login/login-email.php
- dt-login/login-user-manager.php
@corsacca 
Just implementing the recaptcha in zume, so needed to uncomment this.
I imagine I'll need to do a bit of other work on the DT login-template to make sure this is working correctly for DT as well
> chore: uncomment recaptcha check in backend

- dt-posts/posts.php
- dt-workflows/workflows-execution-handler.php
> #2488 - DT Workflows - Updates When Connections Are Triggered On Other Records

- dt-metrics/records/date-range-activity.js
- dt-metrics/records/select-tags-charts.js
- dt-metrics/records/time-charts.js
> #2527 - Metrics Field Selects On One Row

- dt-assets/js/new-record.js
- dt-contacts/access-module.php
- dt-core/global-functions.php
Hi @micahmills 
We have completed the following tasks into this -
1. Integrated Dt-multiselect-button-group into Create new contact form and accurate values posted into API. (dt-core\global-functions.php)
2. Also, Removed JQuery code which was earlier responsible for posting New contacts form data to API, not that is achieved via JavaScript and invoking API from web components API services.
3. Added 'isset()' function into access_module at line: 465. This was added while API hits in case of a single select field - **Contact Status** for fetching data and selecting the desired value throws an error. 
@gp-birender @vijenderrr
> Integrations of Dt-multiselect-button-group into DT Theme

- dt-core/admin/admin-settings-endpoints.php
- dt-core/admin/menu/tabs/tab-customizations.php
> #2551 - Missing Permissions On Role Updates Bug

- archive-template.php
- dt-assets/js/modular-list.js
> #2400 - Split By - Option To Clear Filters

- dt-posts/posts.php
adds a hook to the delete_post API call
> feat: add a hook when deleting a post

- dt-posts/posts.php
> feat: add before post deleted hook

- dt-assets/functions/details-bar.php
- dt-assets/js/new-record.js
- template-new-post.php
@micahmills 
We have made changes in  theme to implemement dt-button for favorite button at the top detail bar. We have made related changes in the dt-button web component, apiService and componentService. Kindly review the changes and provide us with your feedback.
Kindly note that as of now. The `Activity and Comments `section isn't working when we make changes/updations for any element of web components. So, to see the changes logged in the `Activity` section we need to reload/refresh the page
Thank you!
@vijenderrr
> Favorite and Follow Button conversion to DT-Button

- dt-contacts/dmm-module.php
> Change "no answer" quick action to "contact attempted".

- archive-template.php
- dt-assets/js/modular-list.js
Reverts DiscipleTools/disciple-tools-theme#2571
> Revert "DT-List Integration in DT-Theme Contacts List"

- dt-login/login-user-manager.php
also 
fix: use correct user_login from ->data
> fix: trim deprecation warning by passing in dummy password;

- dt-mapping/mapping.js
> #2591 - D.T Mapping - Blank Regions

- dt-core/global-functions.php
- dt-workflows/workflows-execution-handler.php
> #2600 - Workflows: Updating A Quick Action To 0

- dt-core/admin/admin-settings-endpoints.php
- dt-core/admin/components/setup-wizard-celebration.js
- dt-core/admin/components/setup-wizard-controls.js
- dt-core/admin/components/setup-wizard-intro.js
- dt-core/admin/components/setup-wizard-modules.js
- dt-core/admin/components/setup-wizard-plugins.js
- dt-core/admin/components/setup-wizard-use-cases.js
- dt-core/admin/components/setup-wizard.js
- dt-core/admin/js/dt-shared.js
- dt-core/admin/menu/menu-setup-wizard.php
- dt-core/configuration/config-site-defaults.php
> add module step to wizard

- .eslintrc.cjs
- .prettierignore
- cypress.config.js
- cypress/e2e/contacts/create_new_contact.cy.js
- cypress/fixtures/example.json
- cypress/support/commands.js
- cypress/support/e2e.js
- package-lock.json
- package.json
Initial support for the [Cypress Testing Framework](https://www.cypress.io), with a sample `Create New Contact` test. Additional potential tests to be integrated:
- Add Bulk Contacts Records.
- Delete Contact Record.
- Delete Group Record.
- Search For Records.
- Update Contact Record.
- Update Group Record.
> Cypress Testing Framework Integration

- archive-template.php
> #2596 - Bulk Edit Of Mapbox/Google Locations Not Working

- dt-core/utilities/dt-components.php
> #2682 - Custom Icon Does Not Show On Custom Communication Channel Fields

- dt-assets/functions/enqueue-scripts.php
- dt-assets/js/comments.js
- dt-assets/parts/loop-activity-comment.php
- dt-core/dt-storage.php
- dt-posts/dt-posts-endpoints.php
> #2743 - Audio Comment Voice Message Transcriptions

- dt-reports/magic-url-setup.php
For contacts that are connected to a user account, this will display a User Apps tile to users with the manage_dt permission. This allows admin users to copy and share user app links with their users easier than logging in as that user and going to their user profile.
> Add User Apps tile to user contacts
