assets/js/settings.js
template-settings.php

Major simplification of the preferences saving logic. I abandoned the pattern of saving the preference into a single key with an array. It required to much house keeping with regular updating from the users. Instead I moved each preference out to its own key in the meta table. This cleared up an enormous amount of housekeeping code and should produce a more durable format.
https://github.com/DiscipleTools/disciple-tools/pull/181

major simplifications of preference saving logic.

---

dt-assets/functions/breadcrumbs.php

I noticed it on the create new contact page, but there might be more. If there isn't an updated needed or share button, don't display the breadcrumb bar.

Remove breadcrumb bar if there isn't any content

---

dt-assets/js/contact-details.js

This turns the email and phone fields in the contact details page, to links using the `mailto:` and `tel:` protocols.
The `mailto:` link will be useful for people in media roles, when they need to send someone an email.
The `tel:` link will be useful to multipliers, they will be able to call or SMS contacts quicker.

Make email and phone fields clickable in contact details

---

dt-posts/posts.php

When attempting to delete a phone number from a contact via the API, I found it was not being deleted. 
POST to `/wp-json/dt-posts/v2/contacts/{id}`
Body:
```
{
"contact_phone": [{
"delete": true,
"key": "contact_phone_123"
}]
}
```
**Expected**
Should delete phone number so that it is no longer returned from the API. In the database, it should delete metadata records for `contact_phone_123` and `contact_phone_123_details`
**Actual**
Phone number is still returned from the API. In the database, only `contact_phone_123_details` was deleted.
**Fix Description**
When deleting post metadata, this update includes the deletion of both metadata records so that the value is completely deleted.

Delete post metadata value along with details (from API)

---

dt-assets/js/shared-functions.js
dt-metrics/metrics-contacts.php
dt-metrics/metrics-critical-path.php
dt-metrics/metrics-personal.php
dt-metrics/metrics-prayer.php
dt-metrics/metrics-project.php
dt-metrics/metrics-workers.php

get_stylesheet_directory_uri() uses the child theme directory if a child theme is active.  This is not the desired behavior when actually using a child theme.  It results in metrics-personal.js not being properly enqueued, and the Metrics page fails to load.  We should load metrics-personal.js from the parent theme by using get_template_directory_uri() instead to ensure compatibility.

Fix enqueue scripts bug when using a child theme

---

dt-assets/js/shared-functions.js
dt-core/admin/admin-enqueue-scripts.php
dt-mapping/globals.php
dt-metrics/metrics-contacts.js
dt-metrics/metrics-contacts.php
dt-metrics/metrics-critical-path.php
dt-metrics/metrics-personal.php
dt-metrics/metrics-prayer.php
dt-metrics/metrics-project.php
dt-metrics/metrics-workers.php

Patch is for child theme compatibility. Replaces occurrences of get_stylesheet_directory_uri() with get_template_directory_uri() when used to reference critical scripts or files found in parent directory.

Completing child-theme compatibility patch

---

dt-core/admin/restrict-site-access.php

For those wishing to use XML RPC who also understand the risk, this allows setting an environment variable (`XMLRPC_ENABLED=true`) on your server to enable the feature. By default, it is still disabled as was previously the case.
* XMLRPC_ENABLED='true' (string value) (expect: XML-RPC works)
* XMLRPC_ENABLED='false' (string value) (expect: XML-RPC fails)
* XMLRPC_ENABLED not defined (expect: XML-RPC fails)
`POST http://my.disciple.tools/xmlrpc.php`
Body:
```
<?xml version="1.0"?>
<methodCall>
<methodName>wp.getUsers</methodName>
<params>
<param>
<value><int>1</int></value>
<value><string>admin</string></value>
<value><string>badpass</string></value>
</param>
</params>
</methodCall>
```
```
<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<fault>
<value>
<struct>
<member> …
```

Allow configuration of XML-RPC by use of an environment variable

---

dt-assets/parts/group-details.php

(The icon was accidentally left there so was not needed.)

Remove extra icon for group name

---

gulpfile.js
package-lock.json
package.json

On Windows, the CSS and JS files that gulp generates has `\r\n` at line endings instead of `\n`. This change replaces all `\r\n` instances with `\n` to facilitate development on Windows.

change CRLF to LF endings for gulp sourcemaps using gulp-frep

---

dt-assets/js/comments.js
dt-assets/js/list.js
dt-assets/parts/loop-activity-comment.php
dt-core/admin/config-site-defaults.php

fixed the language attribute in Multilingual situations.
Fixes the time stamps and date strings to use localized string, but still uses Gregorian calendar.
Fixes the number formatting in the comments tab.

Format numbers and dates

---

dt-metrics/metrics.php

On the Project Overview metrics dashboard, the Waiting on Accept is not showing the same number as when you filter the contacts list by the same status. It seems to be because the value in the database could be either blank or "no" and the metrics query was only checking for blank.

Fix "Waiting on Accept" Metric

---

dt-posts/posts.php

A contact's creation date is not currently available when using DT_Posts::list_posts, so this adds it in.

Add `post_date` to `search_viewable_post` results

---

dt-assets/js/contact-details.js

fixes a bug in the contact edit modal -> Social Media selector. It was using javascripts native escape() function instead of _.escape() for the channel names. If the users locale was a non-latin script it showed a list of URL encoded non-sense instead of the actual string.

Social Media List escape bug

---

dt-assets/js/comments.js
dt-posts/dt-posts.php

removes escaping from the Javascript so that the PHP gets the unescaped HTML and then applies wp_kses_post() to it to strip out malicious attributes and tags.

Comment Bug Fix

---

dt-core/admin/class-roles.php
dt-core/admin/menu/tabs/tab-general.php
dt-posts/dt-posts.php
dt-posts/posts.php
dt-users/users.php

Adds a Preference pane in Settings (DT) -> General Settings. This lists all the DT Roles and allows you to check the box if you want to allow that role to have access to the DT users on the front end. This will allow things like Assign, Sub-assign, and @ mentions to list all DT Users.

User Visibility by Role Preferences

---

dt-people-groups/people-groups.php

This occurs when you have a translation setup for a people group, the search is looking for matches in both the title and the translation labels. If your search matches both (ie Title - American and Spanish Label - Americano and you search for American) it will return the people group twice. This compares the post ID to create a unique array that is returned.

filtering out duplicates from the people group compact end point.

---

dt-assets/js/details.js
dt-assets/js/group-details.js
dt-assets/js/shared-functions.js

by making all timestamps based on the start of the day utc not the local time

Addresses #1064 going forward

---

dt-assets/parts/merge-details.php

Fixes an issue where the instagram icon for the original contact was too big in the duplicate Contacts modal.

Icon Size in Duplicate Contact Modal

---

dt-core/core-endpoints.php

In order to facilitate greater use of the activity logging, especially for actions that only happen in the client, this exposes an endpoint to save activity logs.

add api endpoint to log activity from front-end

---

dt-posts/dt-posts.php
dt-posts/posts.php

uses wp_specialchars_decode() to fix the HTML encoded characters in contact and group Titles.
wp_specialchars_decode() will handle &, <, >, ", and ‘.
The other PRs for this were a start, but were flawed. So I just started over. I believe I hit all the places that post titles are shown. I checked the Dashboard plugin, lists pages, and individual pages, and various metrics pages.
I also checked it against XSS injections and it seems to hold up, but that is always worth double checking.

HTML Entities in Titles

---

dt-assets/functions/menu.php
dt-metrics/metrics.php
dt-posts/custom-post-type.php

I would like us to use a filter instead of an action to load the menu item for the nav bar and the offcanvas menu items.
The main reasons:
- we can reorganize them if needed or if there are too many links to display
- a org can create a plugin hooking into the filter with a high priority number to reorder them (ie groups first)
- we can change the navbar strategy down the road without needed to change the html in all plugin that add a nav item.

Menus: Use filters instead of actions to load menu items

---

dt-notifications/notifications.php

Before, everything was getting rounded upwards.
eg. 3.2 weeks was considered = 4 weeks.
Additionally, the checks where being made on < 4 weeks ago and > 4 weeks ago but if something was exactly 4 weeks ago it wouldn't appear. This is a problem specially on notifications that fall between the cracks in terms of being equal to X amount of years.

fixed bug that rounds time upwards and doesn't take time gaps

---

dt-notifications/notifications.php

Use WP time settings instead of server settings.
fixes issues #1066

Notification Timezone bug fix

---

dt-core/configuration/class-migration-engine.php
dt-core/migrations/0040-update-reports-value-column.php

This pull request adds a migration to expand the size of the value column in dt_reports from INT(11) to BIGINT(22). This will allow larger numbers to be used. The immediate application is felt in a recurring time scheduling feature.

Enlarge Value Column in the DT_Reports table to handle larger numbers

---

dt-assets/js/new-record.js

brings the People Groups typeahead on the new records page up to date to the details page version.

People Groups typeahead on the new records 

---

dt-assets/js/comments.js

pulls the name for the tooltip from the proper place in the JS global object.

fixes #1170

---

template-new-post.php

fixes the 'hide fields' button showing initially on the add group page.

fix: add display: none; to hide #hide-hidden-fields button initially

---

dt-posts/posts.php

This fixes a bug that if a custom communication channel has a space it would not add an update in the activity section of the comments. 
Basically the space was converted to a underscore and previously we were exploding the string based on underscores. So we were expecting something like `contact_customChannel_d123` and then searched the $post_type_settings["channels"] for the key `customChannel`, this broke when we have something like `contact_custom_channel_d123` because we were be searching the $post_type_settings["channel"] for a key of "custom" instead of "custom_channel".

Adds logic to recombine comm channels with spaces.

---

dt-assets/parts/nav-topbar.php

If theme directory is not named exactly `disciple-tools-theme`, the theme detection in the header does not seem to be working. This can happen from old installs that are named `disciple-tools-theme-master`, so adding this fix to grab the directory name from the current theme.

use current theme stylesheet to get correct update option

---

dt-core/admin/menu/tabs/tab-error-logs.php
dt-workflows/error-log-dispatch-email.php
dt-workflows/error-log-retention-enforcer.php
dt-workflows/workflows.php

- Additional logging settings have been added, so as to (1) Enable/Disable the enforcement of error log retention policy. (2) Specify retention period in days.
- A new cron job [`error_log_retention_enforcer`] has also been added to handle retention policy error log removals.
- Existing dispatch email cron job naming has been changed to [`error_log_dispatch_email`], for uniformity.

1292 - Error Log Retention Policy Management

---

archive-template.php

closes #1329 by adding the white generic icon

set generic icon in mobile view

---

dt-metrics/personal/coaching-tree.php
dt-metrics/personal/group-tree.php

This adds the word 'My' to the start of the page heading to help distinguish this is a personal tree and not the project tree.
Previously:
Now:

'My' coaching and group heading

---

dt-assets/js/modular-list.js

fixes the issue where the user couldn't use the drop down year and month selectors after cd4c7898
resolves #1379

fix: don't run the blur if the user clicked anywhere in the datepicker

---

dt-mapping/geocode-api/google-api.php
dt-mapping/geocode-api/mapbox-api.php

- Mapbox:
- Refactored `is_active_mapbox_key()` logic to also include/display additional error messages.
- Google:
- Implemented is_active_google_key() logic to display additional error messages and check across the following api types:
- Address based search.
- Latitude and longitude coordinates based search.
- Address based search with components.

1374 - Test Geocoding Keys in Admin Area

---

dt-posts/dt-posts.php
dt-posts/posts.php

update_post_user_meta_fields() only needs to be called once to process all the private fields.

Avoid double task creation

---

dt-contacts/duplicates-merging.php

Updated and provided additional merge support for the following post field types:
- multi_select
- key_select
- text
- textarea
- number
- date
- array
- boolean
- tags
- location_meta
- connection
- communication_channel
- tasks
- private fields

1390 - Support Common Field Types During Merging

---

archive-template.php
dt-contacts/access-module.php
dt-core/libraries/posts-to-posts/vendor/scribu/scb-framework/Cron.php
dt-core/libraries/posts-to-posts/vendor/scribu/scb-framework/Forms.php

fix: iron out warnings/errors/deprecations from PHP 8.0 upgrade #1384

---

dt-assets/js/shared-functions.js

The langcode variable was being used several times so in an effort to keep the code DRY I made it its own shared function.

extracted the langcode variable code to its own function

---

dt-core/admin/config-dashboard.php

This parameter allows Google Analytics tracking to see how many people click on the link irregardless what their domain is.

Added link tracking

---

dt-assets/js/comments.js

Bug fix for #1448.
event.submitter only works in Chrome and Firefox not in Safari (desktop or mobile). So we have to use a different method for getting the value of the reaction submit button.

Reaction Click Bug fix

---

dt-contacts/access-module.php
dt-contacts/contacts_access.js

Update Contact Status field when Assigned To has changed
If a contact type is changed to access:
- assign the contact to the user
- set the status to active if there is no status

Contact status fixes

---

dt-assets/functions/details-bar.php

Problem. If you set the dt_print_details_bar param $comment_button false or share false, the html of the page is disrupted.

Fix Details Bar

---

dt-core/admin/menu/tabs/tab-featured-extensions.php

Now, if a plugin is installed but not active, the user can uninstall it from the DT Extensions menu.
This solves the following issue:
https://github.com/DiscipleTools/disciple-tools-theme/issues/1530

Added "Uninstall" Button in DT_Extensions Menu

---

dt-core/admin/menu/tabs/tab-custom-lists.php

_Responds to https://github.com/DiscipleTools/disciple-tools-theme/issues/1608_
Added translation feature to the Quick Actions buttons.
Works for Standard Quick Actions and Custom Quick Actions.
**Admin Settings Page**
<br>
**English Quick Answers (including a custom action)**
<br>
**Spanish Quick Answers (including a custom action)**

Quick actions translate

---

dt-reports/magic-url-base.php

I'm not sure why it isn't registered. The key exists for me locally. I only get this error in our staging environment.

Fixing error when mapbox-search-widget isn’t registered.

---

dt-assets/js/shared-functions.js

courtesy of [webtoolkit.info](http://www.webtoolkit.info/javascript_base64.html#.YnzNAHXRRhE)
this fixes the issue that the modular list query param encoding breaks if any non ascii chars are used in the query

fix: add and use a utf-8 capable base64 encoder and decoder 

---

phpcs.xml

fix: remove regex that mistakenly filters out folders with dots in

---

archive-template.php

hide the archived toggle if the post type isn't set up to make use of it yet

fix: hide the archived toggle if status not ready

---

dt-posts/dt-posts-hooks.php

@kodinkat I noticed this function and the a key that was missing:
dt_get_custom_tile_translations()
Thoughts vs https://github.com/DiscipleTools/disciple-tools-theme/pull/1706 ?

Fix tile label translations

---

dt-assets/js/shared-functions.js

This fixes a bug when using the Prayer Request plugin and for proposed updates in the Meetings plugin. When those post types were created from a contact or group record page it caused the name of the record to update in the details summary tile. It wasn't making the change in the DB, just adjusting the DOM. Previously the assumption was that if there was a record update from a record page it was related to the current record, in the case of these plugins this was not the case.

Adds a post type check on an ajaxComplete event.

---

dt-core/admin/js/dt-utilities-workflows.js
dt-workflows/workflows-execution-handler.php

Adds a checkbox below the datepicker to use current date. When checked, the datepicker is cleared. When a date is selected, the checkbox is unchecked.
Potential issue is that it can cause an infinite loop when it continuously changes a date field because the change of the field would trigger the workflow again. I had to add a condition to my workflow to check if the date field was empty. This could cause unexpected behavior for users who don't know the need for the condition. I tried to change the date to the current date without the time, but it still seems to be having the issue.

Workflow action to set current date

---

dt-core/global-functions.php

Replacing some mb_ functions in case users don't have the multibyte string extension installed.

Replacing mb_strto functions

---

dt-mapping/class-migration-engine.php
dt-mapping/globals.php
dt-mapping/mapping-admin.php
dt-mapping/mapping.js
dt-mapping/migrations/0013-migrate-to-v2.php
dt-metrics/common/maps_library.js

1 of 3 Upgrades. Please approve in order. 
- This version bump migrates up the base google and amazon urls to point to the v2 polygon set.
- This version updates a couple hardcoded subdirectory endpoints for the Amchart metrics.
This step is 1 or 2 upgrades. This will move all DT instances to v2 assets, while continuing to support legacy Amchart 4 charts. It also includes tile sets, m49 sets, and the json_db static database.

Mapping v2a

---

.gitignore
.vscode/.gitignore
.vscode/extensions.json

This vscode specific file will bring a pop-up (hopefully) on someones vscode when they add disciple-tools-theme to their workspace, and give them the option to install the recommended extensions for this workspace.
I've included some php, wordpress and js specific ones as well as some other useful tools that help me every day such as 
* php tools, which adds
* php debug
* php intellisense
* phpcs which highlights your code according to the phpcs.xml in the theme/plugin
* wordpress hooks intellisense - autocompletes wp hook names when writing filters/actions
* eslint for highlighting js eslint issues 
* bracket colourisation
* git lens
* autocompleting html tags
* autorenaming closing html tags
* highlighting translation files nicely
* highlighting those annoying trailing spaces or tabs …

chore: add a list of recommended extensions from the ones that I'm using :)

---

dt-core/configuration/restrict-site-access.php
dt-mapping/geocode-api/mapbox-search-widget.js
dt-mapping/geocode-api/mapbox-users-search-widget.js

Mapbox needs the referrer header in order to work when restricting the key to only work on certain urls.
See:
https://docs.mapbox.com/mapbox-gl-js/guides/browsers-and-testing/#referrer-policies
The current policy is `same-origin` which means any outside link a D.T user clicks on to open does not include the referrer header.
For mapbox api token restriction to work we would need to change the referrer-policy to `strict-origin-when-cross-origin`

Change the request referrer header to `strict-origin-when-cross-origin` which is the new default since 2022

---

dt-posts/custom-post-type.php

This PR would create a "source" for each of the post types and declare the default "CRUD" permissions.

Declare default D.T capabilities for posts

---

dt-mapping/geocode-api/mapbox-search-widget.js

fixes console log error when hitting enter in mapbox widget after selecting an item in the list

fix: check for selection_id existing before closing list

---

dt-contacts/contacts-utils.php
dt-contacts/contacts.php
dt-core/admin/menu/tabs/tab-gdpr.php

moves the erase_data for GDPR purposes out into a utility class.
This will enable other porches/pages etc. (e.g. prayer.global ) to use this erase data GDPR functionality

refactor: move erase_data function into new DT_Contacts_Utils class

---

dt-core/admin/js/dt-options.js

#1898 - Collapsed Safari Translation Dialog

---

dt-posts/dt-posts.php
dt-posts/posts.php

The `list_all_[post_type]` permission was not properly being used at all and was mis-named in the code. This updates `get_viewable_compact` to check the `list_all_` permission and then skip further permission checks in `search_viewable_post`

use `list_all_` permission for viewing compact list

---

dt-core/core-endpoints.php
dt-posts/dt-posts.php

Hey @corsacca 
Is this a bug that these places had an empty array instead of 'contacts' and 'groups' in them?
I was trying to use `DT_Posts::get_post( 'laps', $post_id )` to get a lap and all of it's fields, but the contacts field, which was linked to the contacts post type was getting filtered out, as the `$post_types` field in function `DT_Posts::get_post_field_settings` was returning an empty array.
I think this is because the `dt_registered_post_types` apply filter in function `log_activity` hadn't run yet and added the defaults 'contacts' and 'groups'.
What do you think?
Also I couldn't find any other references to this filter in core, so was wondering where it's being used for the other post types like peoplegroups etc.

fix: default registered post types should always be contacts and groups?

---

dt-core/admin/menu/tabs/tab-customizations.php

Clicking on the 'edit tile' icon for the 'No Tile/Hidden' element resulted in a bug because that element doesn't have tile settings.
**Bug Screenshot:**
Bug was fixed by removing the edit feature in tile-less elements.

Removed 'edit tile' feature for 'no tile/hidden' tile rundown element

---

dt-core/admin/js/dt-settings.js

Added 'field type' label to Edit Field modal

---

dt-core/admin/css/dt-settings.css
dt-core/admin/js/dt-settings.js

Open tile menu shadows were attached to the field element and that made them draggable if the field element was dragged.
- Inset field shadows were turned into Outset tile shadows
- Inset field option shadows were turned into Outset field shadows
- Shadow rendering function was deprecated

Fixed draggable shadows UI bug

---

dt-core/admin/admin-settings-endpoints.php
dt-core/admin/css/dt-settings.css
dt-core/admin/js/dt-settings.js
dt-core/admin/menu/tabs/tab-customizations.php

**Functionality example:**
https://user-images.githubusercontent.com/36511666/236450540-705aeed5-56dc-44fc-9b94-9c7b8cd1fd89.mov
**Refactored some code:**
- Fixed input field's name `edit-tile-label -> new-field-name`
- The `new_field_name`, `new_field_type`, and `new_field_private` elements didn't need to have the tile id in their id name because only one modal is displayed at a time so no ambiguity conflicts should arise.
- Other input fields might have the tile id in their id name but only this one was fixed in order to not broaden the PRs scope

Added field key check functionality before adding field

---

dt-workflows/workflows-execution-handler.php

When setting a condition for a workflow with the `not_contain` comparison but the field is not set at all, the condition was not being matched. However, if the field is not set, we know that it doesn't contain the given value. This handles the case where the field is not set for `not_contain` and `not_equals`

workflows: handle not_equals/not_contain when field is not set

---

dt-core/admin/admin-settings-endpoints.php
dt-core/admin/js/dt-settings.js

The typeahead now includes fields that don't have a tile associated to them.

Added non tiled fields to typeahead

---

dt-metrics/combined/date-range-activity.js
dt-metrics/combined/date-range-activity.php
dt-metrics/metrics.php

- fixes: #1538 
- fixes: #2080 
---
- New Activity During Date Range project metric introduced.
- Metric provides the ability to query post records by field and within a given date range.
- Ability to click-through to listed results post records for more detail.
- Added 2nd level filter support for typeahead based field types: `connection`, `location` & `user_select`.
- Display new value field was updated with.

#1538 - Activity During Date Range Metric

---

dt-posts/dt-posts.php
dt-posts/posts.php

User IDs were being sent as an integer instead of a string like contact ids when requesting a compact.

User IDs were being sent as an integer 

---

dt-metrics/groups/tree.js
dt-metrics/personal/group-tree.js

Found a bug with the modal reveal , where if the assigned_to is not set in the API response, the modal window will not fill.

Bug fix: Modal not opening when assigned_to is empty.

---

dt-metrics/combined/locations-list.js
dt-metrics/combined/locations-list.php

This moves variability back to the php class and allows the .js to be reused by other applications with other urls.

Fix. Location List Endpoints hardwired into the .js. 

---

dt-login/login-endpoints.php

fixes: user having UID as displayname when logging in with email through SSO login UI on Prayer.Global

fix: add firebase Displayname to user manager if not exists

---

dt-login/login-endpoints.php
dt-login/login-user-manager.php

@corsacca 
In PG, there is an issue, where if a user logs in with the admin side which uses PHP, and then comes back to their logged in PG (with JWT token) then it has an issue and can't check the auth properly.
This might be a sledgehammer solution, and not sure if it will have any other repercussions (but I don't think it would)
But would essentially make sure, that if someone is logging in with JWT, that the WP side is logged out first.
This makes sure that the JWT check_auth function continues to work and doesn't lead to any unexpected behaviour where the check_auth doesn't return the user correctly.

fix: clear any WP login cookies before JWT login

---

dt-core/admin/menu/tabs/tab-general.php
dt-core/admin/menu/tabs/tab-security.php
dt-core/configuration/restrict-rest-api.php

Certain third party plugins add API endpoints that needs to not have authentication on them that DT enforces by default. There is currently a filter that can whitelist endpoints via plugin, but this adds a simple way in core to add endpoints that should be allowed to pass through.
For reference, my use case is the Wordfence plugin that has a central dashboard that hits an API endpoint for remote management and configuration.

Allow whitelisting API endpoints to skip DT auth requirement

---

dt-core/admin/admin-settings-endpoints.php
dt-core/admin/js/dt-settings.js
dt-core/admin/menu/tabs/tab-custom-fields.php

Keeps admins from changing private fields to public and vice versa.
This causes issues because the data is stored diferrently.

Disable edit field private

---

dt-users/user-hooks-and-config.php

I was looking into why the contact record wasn't being downgraded and saw this error in the debug.log
```
[05-Aug-2023 08:25:13 UTC] WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'pm
WHERE meta_key = 'corresponds_to_user'
AND pm' at line 1 for query 
DELETE FROM wp_postmeta pm
WHERE meta_key = 'corresponds_to_user'
AND pm.meta_value = 32161
made by wpmu_delete_user, do_action('wpmu_delete_user'), WP_Hook->do_action, WP_Hook->apply_filters, DT_User_Hooks_And_Configuration::dt_multisite_delete_user_contact_meta, DT_User_Hooks_And_Configuration::dt_delete_user_from_blog
```
This doesn't stop the contact record being of the type user, but did mean that the corresponds_to_user meta …

fix: broken query to remove corresponds_to_user

---

dt-core/admin/js/dt-utilities-scripts.js
dt-core/admin/menu/tabs/admin-endpoints.php
dt-core/admin/menu/tabs/tab-background-jobs.php
functions.php

@corsacca Here is my first pass at #2292 for seeing scheduled jobs.
Extra
Next to the button that triggers processing jobs I added some text to indicate the wp_queue cron schedule timing. You can test this by adjusting the interval default here:  
https://github.com/DiscipleTools/disciple-tools-theme/blob/f397541a1871d7d7d5c3864eed00d45d913126c6/dt-core/libraries/wp-queue/WP_Queue/class-queue.php#L62
I tried to add a "countdown" for when the cron schedule would trigger the next processing but [wp_next_scheduled](https://developer.wordpress.org/reference/functions/wp_next_scheduled/) didn't appear to give me accurate info and I didn't know where else to turn.
I wasn't positive where to place the JS to trigger the make_admin_request so I guessed. Feel free to let me know it needs to be …

#2292 - View to see scheduled jobs

---

dt-notifications/notifications-email.php
dt-notifications/notifications.php

Allow emails to have html links in notifications

---

dt-core/configuration/dt-configuration.php

Where a porch is using it's own language switching method, this allows that porch to prevent the html attrs from being switched to match the WP user locale

feat: add filter to override dt_custom_dir_attr

---

dt-login/login-fields.php
dt-login/login-shortcodes.php

We have added a option to show Microsoft as a login option to WP-admin when the custom login option is enabled from the admin.

Add microsoft as sso option to login multisite

---

dt-assets/js/settings.js

Looks like my linter changed a lot of the " to '  and vice versa. But besides that figure I would provide an explanation on what I did: 
I only saw 3 lodash functions in that particular file.  
In this one, declared a new const and made it equal to everything but .dropdown from the original. This allowed me to declare another const, value, and check if .dropdown exists. If it does, great, it will equal .value, otherwise it'll equal 'all'.
```
// return window.lodash.get(window.Typeahead['.js-typeahead-location_grid'].filters.dropdown, 'value', 'all')
const { dropdown } =
window.Typeahead[".js-typeahead-location_grid"].filters;
const value = dropdown?.value ?? "all";
return value;
```
In this case, I used the .sort function. This will check the start_date property in descending order.
``` …
```

coding exercise answers

---

dt-core/configuration/restrict-rest-api.php

Currently, a user could only whitelist endpoints with static paths. This meant that if the endpoint passes a parameter through the URL, it couldn't be whitelisted.
This upgrade allows users to use the star (*) wildcard character in order to whitelist dynamic rest api endpoint paths.
**Screenshot**

Added wildcard character compatibility for DT API Whitelist

---

dt-workflows/workflows-execution-handler.php

When creating a custom action for workflows, it never was getting executed because it couldn't be determined if it had already been executed. This adds another filter so that custom logic for that can be added along with the custom action. It also defaults the value to `false` so that it works even without implementing the new filter.

Create filter for custom actions to indicate if they're already executed

---

dt-metrics/records/genmap.js
dt-metrics/records/genmap.php

#2433 - Dynamic Metrics - Genmapper Filters

---

functions.php

Introducing 2 new actions.
`disciple_tools_load_plugins`
This is where plugins are to be loaded. 
This action is called after the theme is loaded so we can use classes and functions from the theme (but not the DT_Posts API).
`disciple_tools_loaded`
This action is called after the theme and plugins have loaded.
It is now safe to call the DT_Posts API. We will be moving the DT_Posts API to only be available after all the theme and all the plugins have loaded. This is to avoid accidentally using the function too early and getting errors during runtime or only getting a partial return of data. 
Example: using `DT_Posts::get_post_field_settings()` and only getting the theme fields and not any from the plugins.

Create hooks to load plugins and for when the theme is ready.

---

dt-contacts/access-module.php
dt-contacts/base-setup.php
dt-contacts/dmm-module.php
dt-core/admin/menu/tabs/tab-general.php
dt-core/configuration/class-migration-engine.php
dt-core/migrations/0057-enabled-private-contacts.php

Make private contacts an opt-in feature for new instances. Nothing will change on old ones.
This will help with multipliers accidentally creating contacts that should be collaboration contacts.
Fix an issue where contacts were created with the "private connection" type off of a "connection" contact.

Connection types

---

dt-core/admin/admin-settings-endpoints.php
dt-core/admin/js/dt-options.js
dt-core/admin/menu/tabs/admin-endpoints.php
dt-core/admin/menu/tabs/tab-custom-fields.php

This fixes two issues. The second was found after I fixed the first, so I included them in one issue.
Can't save option translations if the option key contains a hyphen.
- Go to Settings (D.T) -> Fields
- Edit a key_select/dropdown field
- Add an option with a hyphen (e.g. "Type - Subtype")
- Add a translation for the given option (e.g. English: "Subtype")
- Refresh page to view updated options
**Expect**: Translation is saved for given option
**Actual**: Translation is not saved. Cause is that the locale is not parsed properly because the code split on a hyphen, expecting no hyphens in the option key.
Saving a translation of a custom option will clear the `label` property of the option.
- Go to Settings (D.T) -> Fields
- Edit a key_select/dropdown field
- Add any custom option (this …

Fix errors saving dropdown option translations

---

dt-metrics/records/genmap.js
dt-metrics/records/genmap.php

#2495 - Metrics - Personal - Gen-Map - Restrict To Records Responsible For

---

dt-metrics/counters/counter-post-stats.php
dt-metrics/metrics.php
dt-metrics/records/select-tags-charts.js
dt-metrics/records/select-tags-charts.php
dt-metrics/records/time-charts.js
dt-metrics/records/time-charts.php

#2496 - Select & Tags Cumulative Activity Metrics Charts

---

dt-users/user-management.php

I found that when giving a multiplier user the User Manager role, they weren't seeing a link on the User Management page to Add Users. I found it was because the code was only checking for `manage_dt` instead of `create_users`, so I added that to the permission check. User Managers who are not DT Admins can now see the Add User link.

Check for create_users permission when displaying Add User submenu

---

functions.php

Implemented `random_bytes_no_null()` wrapper function, to ensure `random_bytes()` do not contain null characters; which cause a `ValueError` exception; following the addition of the [Bcrypt password must not contain null character](https://github.com/php/php-src/commit/6a5c04d01d#diff-97027f2a7f32316e1a9d2317ecd1abd1eca58b9bb9c30c7929c7a33b93df5ad5R184) check.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1208382720655232

Safeguard Against ValueError Bcrypt Null Chars Exceptions

---

dt-core/admin/menu/tabs/tab-security.php
dt-core/admin/site-link-post-type.php

This will let site links work on instances behind a VPN that are set up as localhost.
Or with local dev when debug is false.

Option to disable site link HTTPS check

---

dt-mapping/class-migration-engine.php
dt-mapping/globals.php
dt-mapping/location-grid-list-api.php
dt-mapping/mapping-admin.php
dt-mapping/mapping-queries.php
dt-mapping/migrations/0004-location-grid-table.php
dt-mapping/migrations/0005-prepare-location-grid-data.php
dt-mapping/migrations/0006-add-grid-to-db.php
dt-mapping/migrations/0010-add-location-grid-meta-tb.php
dt-mapping/migrations/0013-v2-options-upgrade.php
dt-mapping/migrations/0014-v2-db-upgrade-optional.php
dt-mapping/migrations/0015-v2-migrate-custom-locations.php
dt-mapping/migrations/0016-restore-table.php
dt-mapping/migrations/0018-check-east-west.php
dt-mapping/migrations/0019-level-is-null.php
functions.php

Add this to a mu-plugin:
```
add_filter( 'dt_location_grid_table', function ( $table_name ){
global $wpdb;
return $wpdb->base_prefix . 'location_grid';
} );
add_filter( 'dt_using_multisite_location_grid_table', '__return_true' );
```
and save 10 to 15MB per subsite by only using one location grid table
To get an sql statement to drop all the location_grid tables:
```
SELECT CONCAT( 'DROP TABLE ', GROUP_CONCAT(table_name) , ';' ) 
AS statement FROM information_schema.tables 
WHERE table_name LIKE '%dt_location_grid';
```

Option to only install location grid once on a multisite.

---

dt-core/admin/admin-settings-endpoints.php

Previously it was getting the full modules details (name, description, etc) and saving it to the option.
We only want the 'enabled' param to be saved to the options.
We want the code to be driving the module descriptions and name instead of it coming from the options table.

Fix saving enabled and disable modules.

---

dt-core/admin/components/setup-wizard-celebration.js
dt-core/admin/components/setup-wizard-intro.js
dt-core/admin/components/setup-wizard-keys.js
dt-core/admin/components/setup-wizard-modules.js
dt-core/admin/components/setup-wizard-plugins.js
dt-core/admin/menu/menu-setup-wizard.php

Feat/setup wizard Wordings

---

dt-assets/js/modular-list.js

#2666 - Resolve CSV Export All Fields Bug 

---

dt-assets/functions/details-bar.php
dt-assets/functions/enqueue-scripts.php
dt-assets/js/dt-storage.js
dt-posts/posts.php

Adds a modal so when the record image is clicked it shows a larger thumbnail. If the image does not exist it functions as before. If it does exist it opens a larger version with a button to replace the image which opens the previous upload modal
This is related to https://github.com/DiscipleTools/disciple-tools-storage/pull/34

Record Images Click to enlarge

---

dt-assets/js/settings.js

This PR replaces lodash functions with ES6 equivalents in the settings.js file:
- Replace `lodash.orderBy` with native JavaScript sort
- Replace `lodash.get` with optional chaining and nullish coalescing operators
Fixes #2398
Resolves #2398
Part of the larger effort in #2361 to replace lodash functions with vanilla JS/ES6 functions

Replace lodash functions with ES6 equivalents in settings.js

---

dt-metrics/counters/counter-post-stats.php
dt-metrics/records/time-charts.js
package-lock.json

- fixes: #2587 
---
All Key Select options are now displayed, even if newly created, with no value.

#2587 - Display All Metric User Key Select Options

---

dt-contacts/base-setup.php
dt-contacts/module-access.php
dt-contacts/module-coaching.php

Disable this: When in adding a new user, the new user contact record would automatically be marked as coached by the user who invited them. This ins't always accurate or wanted. Better place for a workflow.
Filters:
Add new "users" line to the filters list.
By default the All contacts doesn't show users:
Users will be show in the the Users filter.
The rest of the filters don't exclude or include users specifically. 
Fixes https://github.com/DiscipleTools/disciple-tools-theme/issues/2348
Fixes https://github.com/DiscipleTools/disciple-tools-theme/issues/2767

Users in contacts list
